$activeBorderColor = rgb(8b5cf6)
$inactiveBorderColor = rgb(3a2a4d)
$activeShadowColor = rgba(8b5cf6aa)
$inactiveShadowColor = rgba(3a2a4d55)

general {
    col.active_border = $activeBorderColor
    col.inactive_border = $inactiveBorderColor
}

group {
    col.border_active = $activeBorderColor
    col.border_inactive = $inactiveBorderColor
}

decoration {
    rounding = 8
    rounding_power = 3

    shadow {
        enabled = true
        range = 18
        render_power = 4
        color = $activeShadowColor
        color_inactive = $inactiveShadowColor
    }
}
